### ISSUE TITLE
Bot fails to play audio - asking for opus packe but already installed

### ISSUE THREAD

**Issue by AndyMG21** [Pilgrimeru/Pilzic#3]
Every time I play audio on Discord it says that it could not find opus... but that package is already installed.
Checked Google and other sources but nothing, here is the error (censored my name with "user")

```
Error: Error: Cannot find module '@discordjs/opus'
Require stack:
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\util\loader.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\Opus.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\index.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\index.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\@discordjs\voice\dist\index.js
- C:\Users\User\Documents\Software\Pilzic\src\commands\insert.ts
- C:\Users\User\Documents\Software\Pilzic\src\components\Bot.ts
- C:\Users\User\Documents\Software\Pilzic\src\index.ts
Error: Cannot find module 'node-opus'
Require stack:
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\util\loader.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\Opus.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\index.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\index.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\@discordjs\voice\dist\index.js
- C:\Users\User\Documents\Software\Pilzic\src\commands\insert.ts
- C:\Users\User\Documents\Software\Pilzic\src\components\Bot.ts
- C:\Users\User\Documents\Software\Pilzic\src\index.ts
Error: Cannot find module 'opusscript'
Require stack:
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\util\loader.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\Opus.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\index.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\index.js
- C:\Users\User\Documents\Software\Pilzic\node_modules\@discordjs\voice\dist\index.js
- C:\Users\User\Documents\Software\Pilzic\src\commands\insert.ts
- C:\Users\User\Documents\Software\Pilzic\src\components\Bot.ts
- C:\Users\User\Documents\Software\Pilzic\src\index.ts
    at Object.loader [as require] (C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Decoder (C:\Users\User\Documents\Software\Pilzic\node_modules\prism-media\src\opus\Opus.js:183:1)
    at Object.transformer (C:\Users\User\Documents\Software\Pilzic\node_modules\@discordjs\voice\src\audio\TransformerGraph.ts:123:21)
    at C:\Users\User\Documents\Software\Pilzic\node_modules\@discordjs\voice\src\audio\AudioResource.ts:275:57
    at Array.map (<anonymous>)
    at createAudioResource (C:\Users\User\Documents\Software\Pilzic\node_modules\@discordjs\voice\src\audio\AudioResource.ts:275:38)
    at Song.makeResource (C:\Users\User\Documents\Software\Pilzic\src\components\Song.ts:158:31)
```
    
Thanks.

**Comment by Pilgrimeru** [comment]
Thank you for your interest in my project.  The problem is that the 'discordjs/opus' dependency is missing.  I advise you to update Nodejs to the latest LTS version.  Then clone the project again and run the 'npm install' command.
